---
title: "Figure Subcaptions Example"
format: pdf
---

```{r}
cap1 <- 'Speed vs Distance'
cap2 <- "Weight vs MPG"
cap3 <- "HP vs MPG"

# Set chunk options
knitr::opts_chunk$set(
  fig.subcap = c(cap1, cap2, cap3)
)

ll <- list("mpg", "cyl", "gear")

sapply(ll, function(x) paste0("Var: ", x))

```
```{r}
#| label: fig-cars
#| fig-cap: "Relationship between car attributes"
#| layout-ncol: 2
#| fig-height: 3
#| fig-width: 4


# Plot 1: Speed vs Distance
plot(cars$speed, cars$dist, 
     main = "Speed vs Distance", 
     xlab = "Speed", ylab = "Distance")

# Plot 2: Weight vs MPG  
plot(mtcars$wt, mtcars$mpg,
     main = "Weight vs MPG",
     xlab = "Weight", ylab = "MPG")

# Plot 3: Horsepower vs MPG
plot(mtcars$hp, mtcars$mpg,
     main = "HP vs MPG", 
     xlab = "Horsepower", ylab = "MPG")
```

You can reference the overall figure as @fig-cars, or individual subfigures as @fig-cars-1, @fig-cars-2, and @fig-cars-3.
See @fig-cars-1 for the speed relationship, @fig-cars-2 for weight analysis, and @fig-cars-3 for horsepower comparison.